language: go
install: go get -v github.com/spf13/hugo
script:
      - sudo python -m pip install s3cmd
      - s3cmd sync -r s3://marache.net-static static
      - hugo --buildDrafts --theme  hugo_theme_robust
      - s3cmd sync --delete-removed -P -M -r public/ s3://test.marache.net
notifications:
    email:
        on_failure: always

