language: python
install: curl -L https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_extended_0.70.0_Linux-64bit.tar.gz | tar -zx hugo
script:
      - sudo python -m pip install s3cmd Pygments
      - mkdir static
      - s3cmd sync --no-preserve -r s3://marache.net-static static
      - ./hugo
      - s3cmd sync --delete-removed -P -M -r public/ s3://test.marache.net
notifications:
    email:
        on_failure: always

